export const FILTER_TABLE="FILTER_TABLE";
export const SHOWINFOR= "SHOWINFOR";
export const DANHSACH = "DANHSACH";
export const FORMDANGNHAP="FORMDANGNHAP";
export const FORMDANGKI ="FORMDANGKI";
export const THONGBAO ="THONGBAO";
export const TAIKHOAN ="TAIKHOAN";
export const DANGNHAP ="DANGNHAP";
export const DANGXUAT ="DANGXUAT";


export const API_CALL_REQUEST="API_CALL_REQUEST";
export const API_CALL_REQUEST_SUCCESS="API_CALL_REQUEST_SUCCESS";
export const API_CALL_REQUEST_FAILD ="API_CALL_REQUEST_FAILD";


export const API_USER_CALL_REQUEST="API_USER_CALL_REQUEST";
export const FETCH_TASK_USER_SUCCESS="FETCH_TASK_USER_SUCCESS";
export const FETCH_TASK_USER_FAILD ="API_USER_CALL_REQUEST_FAILD";

export const API_ADD_TODO_CALL_REQUEST="API_ADD_TODO_CALL_REQUEST";
export const FETCH_ADD_TODO_SUCCESS="FETCH_ADD_TODO_SUCCESS";
export const FETCH_ADD_TODO_FAILD ="FETCH_ADD_TODO_FAILD";

export const FETCH_TASK_LOGIN_SUCCESS="FETCH_TASK_LOGIN_SUCCESS";
export const FETCH_TASK_LOGIN_FAILD="FETCH_TASK_LOGIN_FAILD";


export const FETCH_TASK_EXERCISE_SUCCESS="FETCH_TASK_EXERCISE_SUCCESS"
export const FETCH_TASK_EXERCISE_FAILD="FETCH_TASK_EXERCISE_FAILD"



